config/routes.rb
Rails.application.routes.draw do

  resources :movements
  resources :stocks
  resources :items
  resources :sectors
  resources :floors
  resources :images
  resources :types
  resources :statuses

  root to: 'movements#index'

  #routes to moves items
  post 'to_move', to: 'movements#to_move', as: :to_move

  #route fo comunication with app
  get 'tag_to_move:id_item', to: 'movements#tag_to_move'
  get 'items_to_app', to: 'items#items_to_app'
  get 'movements_to_app', to: 'movements#movements_to_app'
  get 'images_to_app', to: 'images#images_to_app'
  post 'app_to_move', to: 'movements#app_to_move'

  #routes test
  #get 'test_app_move', to: 'movements#test_app_move', :via => [ :post]




  #Report route
  get 'reports', to: 'movements#reports', as: :reports
  #Reports
  get 'for_product', to: 'movements#for_product', as: :for_product
  get 'for_sector', to: 'movements#for_sector', as: :for_sector
  get 'for_floor', to: 'movements#for_floor', as: :for_floor
  get 'availability_moves', to: 'movements#availability_moves', as: :availability_moves
  #Availabilities
  get 'availables_status', to: 'statuses#availables_status', as: :availables_status
  get 'availables_items', to: 'items#availables_items', as: :availables_items
  get 'availables_moves', to: 'movements#availables_items', as: :availables_moves
  get 'timeline', to: 'movements#timeline', as: :timeline





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def availables_status
    @statuses = Status.available
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:name, :describe)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= form_with(model: status, local: true) do |form| %>
  <% if status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :status_name %>
  </div>

  <div class="field">
    <%= form.label :describe %>
    <%= form.text_area :describe, id: :status_describe %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/statuses/availables_status.html.erb
<p id="notice"><%= notice %></p>

<h1>Avaible's Status</h1>

<div class="col-xs-12">
  <div class="box">
    <!-- /.box-header -->
    <div class="box-body table-responsive no-padding">
      <table class="table table-hover">
        <thead>
        <tr>
          <th>Id</th>
          <th>Name</th>
          <th>Describe</th>
        </tr>
        </thead>
        <tbody>
        <% @statuses.each do |status| %>
            <tr>
              <td><%= status.id %></td>
              <td><%= status.name %></td>
              <td><%= status.describe %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Statuses</h1>

<div class="col-xs-12">
  <div class="box">
    <!-- /.box-header -->
    <div class="box-body table-responsive no-padding">
      <table class="table table-hover">
        <thead>
        <tr>
          <th>Name</th>
          <th>Describe</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
        <% @statuses.each do |status| %>
            <tr>
              <td><%= status.name %></td>
              <td><%= status.describe %></td>
              <td><%= link_to 'Show', status %></td>
              <td><%= link_to 'Edit', edit_status_path(status) %></td>
              <td><%= link_to 'Destroy', status, method: :delete, data: {confirm: 'Are you sure?'} %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>

  </div>
  <%= link_to 'New Status', new_status_path, class: 'btn btn-default' %>
</div>

app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @status.name %>
</p>

<p>
  <strong>Describe:</strong>
  <%= @status.describe %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>