config/routes.rb
Rails.application.routes.draw do

  resources :movements
  resources :stocks
  resources :items
  resources :sectors
  resources :floors
  resources :images
  resources :types
  resources :statuses

  root to: 'movements#index'

  #routes to moves items
  post 'to_move', to: 'movements#to_move', as: :to_move

  #route fo comunication with app
  get 'tag_to_move:id_item', to: 'movements#tag_to_move'
  get 'items_to_app', to: 'items#items_to_app'
  get 'movements_to_app', to: 'movements#movements_to_app'
  get 'images_to_app', to: 'images#images_to_app'
  post 'app_to_move', to: 'movements#app_to_move'

  #routes test
  #get 'test_app_move', to: 'movements#test_app_move', :via => [ :post]




  #Report route
  get 'reports', to: 'movements#reports', as: :reports
  #Reports
  get 'for_product', to: 'movements#for_product', as: :for_product
  get 'for_sector', to: 'movements#for_sector', as: :for_sector
  get 'for_floor', to: 'movements#for_floor', as: :for_floor
  get 'availability_moves', to: 'movements#availability_moves', as: :availability_moves
  #Availabilities
  get 'availables_status', to: 'statuses#availables_status', as: :availables_status
  get 'availables_items', to: 'items#availables_items', as: :availables_items
  get 'availables_moves', to: 'movements#availables_items', as: :availables_moves
  get 'timeline', to: 'movements#timeline', as: :timeline





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  # GET /types.json
  def index
    @types = Type.all
  end

  # GET /types/1
  # GET /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params.require(:type).permit(:name, :describe)
    end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/types/_form.html.erb
<%= form_with(model: type, local: true) do |form| %>
  <% if type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :type_name %>
  </div>

  <div class="field">
    <%= form.label :describe %>
    <%= form.text_area :describe, id: :type_describe %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Types</h1>

<div class="col-xs-12">
  <div class="box">
    <!-- /.box-header -->
    <div class="box-body table-responsive no-padding">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Describe</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @types.each do |type| %>
            <tr>
              <td><%= type.name %></td>
              <td><%= type.describe %></td>
              <td><%= link_to 'Show', type %></td>
              <td><%= link_to 'Edit', edit_type_path(type) %></td>
              <td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<br>

<%= link_to 'New Type', new_type_path %>

app/views/types/new.html.erb
<h1>New Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @type.name %>
</p>

<p>
  <strong>Describe:</strong>
  <%= @type.describe %>
</p>

<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>