config/routes.rb
Rails.application.routes.draw do

  resources :movements
  resources :stocks
  resources :items
  resources :sectors
  resources :floors
  resources :images
  resources :types
  resources :statuses

  root to: 'movements#index'

  #routes to moves items
  post 'to_move', to: 'movements#to_move', as: :to_move

  #route fo comunication with app
  get 'tag_to_move:id_item', to: 'movements#tag_to_move'
  get 'items_to_app', to: 'items#items_to_app'
  get 'movements_to_app', to: 'movements#movements_to_app'
  get 'images_to_app', to: 'images#images_to_app'
  post 'app_to_move', to: 'movements#app_to_move'

  #routes test
  #get 'test_app_move', to: 'movements#test_app_move', :via => [ :post]




  #Report route
  get 'reports', to: 'movements#reports', as: :reports
  #Reports
  get 'for_product', to: 'movements#for_product', as: :for_product
  get 'for_sector', to: 'movements#for_sector', as: :for_sector
  get 'for_floor', to: 'movements#for_floor', as: :for_floor
  get 'availability_moves', to: 'movements#availability_moves', as: :availability_moves
  #Availabilities
  get 'availables_status', to: 'statuses#availables_status', as: :availables_status
  get 'availables_items', to: 'items#availables_items', as: :availables_items
  get 'availables_moves', to: 'movements#availables_items', as: :availables_moves
  get 'timeline', to: 'movements#timeline', as: :timeline





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :status
  belongs_to :sector
  belongs_to :type
  belongs_to :image

  scope :availables, -> {where(status: Status.available)}
  scope :unavailables, -> {where(status: Status.unavailable)}

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.paginate(:page => params[:page], :per_page => 5).order(:name)
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def items_to_app

    items = Item.all
    render json: items

  end

  def availables_items
    @items = Item.availables
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :alias, :describe, :bar_code, :status_id, :sector_id, :type_id, :image_id, :price)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :item_name %>
  </div>

  <div class="field">
    <%= form.label :alias %>
    <%= form.text_field :alias, id: :item_alias %>
  </div>

  <div class="field">
    <%= form.label :describe %>
    <%= form.text_area :describe, id: :item_describe %>
  </div>

  <div class="field">
    <%= form.label :bar_code %>
    <%= form.text_field :bar_code, id: :item_bar_code %>
  </div>

  <div class="field">
    <%= form.label :status_id %>
    <%= form.select(:status_id, options_for_select(Status.all.collect {|f|[f.name, f.id]}, selected: @item.status_id)) %>
  </div>

  <div class="field">
    <%= form.label :sector_id %>
    <%= form.select(:sector_id, options_for_select(Sector.all.collect {|f|[f.name, f.id]}, selected: @item.sector_id)) %>
  </div>

  <div class="field">
    <%= form.label :type_id %>
    <%= form.select(:type_id, options_for_select(Type.all.collect {|f|[f.name, f.id]}, selected: @item.type_id)) %>
  </div>

  <div class="field">
    <%= form.label :image_id %>
    <%= form.select(:image_id, options_for_select(Image.all.collect {|f|[f.url, f.id]}, selected: @item.image_id)) %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :item_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/availables_items.html.erb
<p id="notice"><%= notice %></p>

<h1>Avaibles Items</h1>

<div class="col-xs-12">
  <div class="box">
    <!-- /.box-header -->
    <div class="box-body table-responsive no-padding">
      <table class="table table-hover">
        <thead>
        <tr>
          <th>Alias</th>
          <th>Describe</th>
          <th>Bar code</th>
          <th>Status</th>
          <th>Sector</th>
          <th>Type</th>
          <th>Price</th>
        </tr>
        </thead>
        <tbody>
        <% @items.each do |item| %>
            <tr>
              <td><%= item.alias %></td>
              <td><%= item.describe %></td>
              <td><%= item.bar_code %></td>
              <td><%= item.status.name %></td>
              <td><%= item.sector.name %></td>
              <td><%= item.type.name %></td>
              <td><%= item.price %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= link_to 'Items', items_path, class: "btn btn-default" %>
</div>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-12">
  <div class="box">
    <div class="box-header">
      <h1>Items</h1>
    </div>
    <!-- /.box-header -->
    <div class="box-body table-responsive no-padding">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Alias</th>
            <th>Describe</th>
            <th>Bar code</th>
            <th>Status</th>
            <th>Sector</th>
            <th>Type</th>
            <th>Price</th>
            <th colspan="3">
              <%= link_to "Availables Items", availables_items_path, class: "btn btn-default" %>
              <%= link_to 'New Item', new_item_path, class: "btn btn-default" %>
            </th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td><%= item.alias %></td>
              <td><%= item.describe %></td>
              <td><%= item.bar_code %></td>
              <td><%= item.status.describe %></td>
              <td><%= item.sector.name %></td>
              <td><%= item.type.name %></td>
              <td><%= item.price %></td>
              <td><%= link_to 'Show', item %></td>
              <td><%= link_to 'Edit', edit_item_path(item)%></td>
              <td>
                <%= button_to "Move", to_move_path, class:"btn btn-default", style:"", method: :post, remote: true, params: { item_id: item.bar_code } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div>
    <%= will_paginate @items, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Alias:</strong>
  <%= @item.alias %>
</p>

<p>
  <strong>Describe:</strong>
  <%= @item.describe %>
</p>

<p>
  <strong>Bar code:</strong>
  <%= @item.bar_code %>
</p>

<p>
  <strong>Status:</strong>
  <%= @item.status.name %>
</p>

<p>
  <strong>Sector:</strong>
  <%= @item.sector.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @item.type.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @item.image.url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>